mount_directory: /mydata
key_space: 12000000
slots: 12001000
scr_size: 4GB
logical_scr_size: 200MB
ncr_size: 52GB
local_size: 8GB
replicate: false
flush: false
evict: false
excluded_files:
partition_ratio: 1.0
excluded_directories:
  - /usr
  - /proc
  - /etc
  - /dev
  - /sys