server_id: 0
mount_directory: /mydata
id: 0
host_address: localhost:50051
key_space: 1800000
slots: 30001000
scr_size: 2GB
logical_scr_size: 200MB
ncr_size: 36GB
local_size: 36GB
replicate: false
move_to_share: false
flush: false
evict: false
base_address: 0x6e0000000000
excluded_files:
partition_ratio: 1.0
excluded_directories:
  - /usr
  - /proc
  - /etc
  - /dev
  - /sys